
# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew 

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: List Build Directory
      run: ls -R build

    - name: Create Dockerfile
      run: |
          echo "FROM openjdk:17-jdk-slim" > Dockerfile
          echo "COPY build/libs/rock-paper-scissors-0.0.1-SNAPSHOT.jar /app/rock-paper-scissors-0.0.1-SNAPSHOT.jar" >> Dockerfile
          echo "EXPOSE 8080" >> Dockerfile
          echo 'CMD ["java", "-jar", "/app/rockpaperscissor.jar"]' >> Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Build Docker Image
      run: docker build -t snehalmore94/rockpaperscissor:latest .

    - name: Push Docker Image
      run: docker push snehalmore94/rockpaperscissor:latest


