
# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew 

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Create Dockerfile
      run: |
          echo "FROM openjdk:17-jdk-slim" > Dockerfile
          echo "COPY build/libs/rockpaperscissor.jar /app/rockpaperscissor.jar" >> Dockerfile
          echo "EXPOSE 8080" >> Dockerfile
          echo 'CMD ["java", "-jar", "/app/rockpaperscissor.jar"]' >> Dockerfile

    - name: Build and push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: snehalmore94/rockpaperscissor
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}


